name: Release and publish tsshd
on:
  release:
    types: [released]
jobs:
  release-and-publish:
    name: Release and publish tsshd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tsshd
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean --skip=publish
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.rpm
            dist/*_checksums.txt
      - name: Publish rpm to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          for filename in dist/tsshd*.rpm; do
            curl -F package=@"$filename" https://{$FURY_TOKEN}@push.fury.io/trzsz/
          done
